
[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    "php artisan storage:link",
    "php artisan migrate --force",
    "php artisan optimize"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
