
[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.opcache",
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql", 
    "php82Extensions.mysqli",
    "php82Extensions.curl",
    "php82Extensions.gd",
    "php82Extensions.mbstring",
    "php82Extensions.zip",
    "php82Extensions.xml",
    "php82Extensions.dom",
    "php82Extensions.bcmath",
    "php82Extensions.redis",
    "php82Extensions.fileinfo",
    "php82Extensions.tokenizer",
    "php82Extensions.ctype",
    "php82Extensions.openssl",
    "composer",
    "nodejs_22"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci --only=production",
    "npm run build"
]

[phases.build]
cmds = [
	"php artisan key:generate --force",
    "php artisan storage:link",
    "php artisan migrate --force",
    "php artisan optimize:clear",
    "php artisan optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"